config/routes.rb
Salesiana::Application.routes.draw do
  resources :alunos
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  def index
    @alunos = Aluno.all
  end

  def edit
    @aluno = Aluno.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/edit.html.erb
<h1>Editar</h1>

<div class="content-fluid">
  <div class="row-fluid">
    <div class="span12">
      <%= form_for @aluno do |f| %>
        <div class="row-fluid">
          <%= f.label :nome %>
          <%= f.text_field :nome, class: 'input-block-level' %>
        </div>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <p><%= f.submit "Salvar" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/alunos/index.html.erb
<h1>Aqui vem a lista de alunos</h1>

<table border="1" width="100%">
  <tr>
    <th>Nome</th>
    <th>E-mail</th>
    <th>-</th>
  </tr>

  <% @alunos.each do |aluno| %>
    <td><%= aluno.nome %></td>
    <td><%= aluno.email %></td>
    <td>
      <%= link_to "Editar", edit_aluno_path(aluno) %>
    </td>
  <% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salesiana</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>